default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dev_shop

test:
  <<: *default
  database: test_shop

production:
  <<: *default
  database: prod_shop
